#! /bin/sh 
### BEGIN INIT INFO
# Provides: radio
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: radio program
# Description:
### END INIT INFO 
case "$1" in
start)
        echo "radio started"
        python /home/kradio/raspiradio/prog/radio.py
        ;;
    stop)
        echo "radio stopped"
        killall python
        killall mpd        
        ;;
    *)
        echo "Use /etc/init.d/radio {start|stop}"
        exit 1
        ;;
esac 
exit 0

