#! /bin/bash
### BEGIN INIT INFO
# Provides: radio
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: radio program
# Description:
### END INIT INFO
case "$1" in
start)
        echo -n "Starting radio..."
        python /home/kradio/raspiradio/prog/radio.py
        echo "radio started"
        ;;
    stop)
        echo -n "Stopping radio..."
        killall python
        killall mpd
        echo "stopped"
        ;;
    *)
        echo "Use /etc/init.d/radio {start|stop}"
        exit 1
        ;;
esac
exit 0

